from main.models import Question, Subject

physics_subject = Subject.objects.get(name="Physics")

questions = {
    81: {
        'question': r"A mass-spring system consists of a mass (\(m = 0.5 \, {kg}\)) attached to a spring with a spring constant (\(k = 200 \, {N/m}\)). The system is placed on a frictionless horizontal surface and the mass is displaced by 0.1 m from its equilibrium position and released from rest. A. Calculate the angular frequency (\( \omega \)) of the oscillations. B. Determine the maximum speed of the mass during the oscillation. C. At what displacement (\( x \)) from the equilibrium position is the speed of the mass half of the maximum speed?",
        'answer': r"(a) Angular Frequency: The angular frequency (\( \omega \)) of a mass-spring system is given by: \( \omega = \sqrt{\frac{k}{m}} \). Substituting the given values: \( \omega = \sqrt{\frac{200 \, {N/m}}{0.5 \, {kg}}} = \sqrt{400 \, {rad}^2/{s}^2} = 20 \, {rad/s} \). (b) Maximum Speed:} The maximum speed (\( v_{{max}} \)) is given by: \( v_{{max}} = \omega A \) where \( A \) is the amplitude. Given \( A = 0.1 \, {m} \): \( v_{{max}} = 20 \, {rad/s} \times 0.1 \, {m} = 2 \, {m/s} \). (c) Displacement at Half Maximum Speed:} The speed (\( v \)) at a displacement (\( x \)) is given by: \( v = \omega \sqrt{A^2 - x^2} \). Given \( v = \frac{v_{{max}}}{2} = 1 \, {m/s} \): \( 1 \, {m/s} = 20 \, {rad/s} \sqrt(0.1 \, {m})^2 - x^2} \). \( \frac{1}{20} = \sqrt{0.01 - x^2} \). \( 0.0025 = 0.01 - x^2 \). \( x^2 = 0.01 - 0.0025 = 0.0075 \). \( x = \sqrt{0.0075} = 0.0866 \, {m} \).",
        'paper': 2
    },
    82: {
        'question': r"Photons of wavelength 468 nm are incident on a metallic surface. The maximum kinetic energy of the emitted electrons is 1.8 eV. A. Calculate the work function of the surface, in eV. B. Calculate the longest wavelength of a photon that will eject an electron from this surface. C. The photoelectric effect experiment is conducted with a different metallic surface that has a work function of 2.2 eV. If the incident photons have the same wavelength of 468 nm, calculate the new maximum kinetic energy of the emitted electrons.",
        'answer': r"(a) Work Function: The energy of the incident photons is given by: \( E = \frac{hc}{\lambda} \). Substituting the given values: \( E = \frac{4.135667696 \times 10^{-15} \, {eV·s} \times 3 \times 10^8 \, {m/s}}{468 \times 10^{-9} \, {m}} \approx 2.65 \, {eV} \). The work function (\( \phi \)) is then: \( \phi = E - KE_{{max}} \). \( \phi = 2.65 \, {eV} - 1.8 \, {eV} = 0.85 \, {eV} \). (b) Longest Wavelength: The longest wavelength (\( \lambda_{{max}} \)) is given by: \( \phi = \frac{hc}{\lambda_{{max}}} \). Rearranging for \( \lambda_{{max}} \): \( \lambda_{{max}} = \frac{hc}{\phi} \). \( \lambda_{{max}} = \frac{4.135667696 \times 10^{-15} \, {eV·s} \times 3 \times 10^8 \, {m/s}}{0.85 \, {eV}} \approx 1.46 \times 10^{-6} \, {m} \) or 1460 nm. (c) New Maximum Kinetic Energy: The energy of the incident photons remains the same: \( E = 2.65 \, {eV} \). The new work function (\( \phi' \)) is 2.2 eV. The new maximum kinetic energy (\( KE_{{max}}' \)) is given by: \( KE_{{max}}' = E - \phi' \). \( KE_{{max}}' = 2.65 \, {eV} - 2.2 \, {eV} = 0.45 \, {eV} \).",
        'paper': 2
    },
    83: {
        'question': r"A long straight wire carries a current of 5 A. A proton is moving parallel to the wire with a speed of \( 1.5 \times 10^6 \, {m/s} \) at a distance of 0.02 m from the wire. A. Calculate the magnetic field strength at the location of the proton due to the current in the wire. B. Determine the magnitude of the force acting on the proton due to the magnetic field. C. Find the direction of the force acting on the proton.",
        'answer': r"(a) Magnetic Field Strength:} The magnetic field strength (\( B \)) at a distance (\( r \)) from a long straight wire carrying a current (\( I \)) is given by: \( B = \frac{\mu I}{2 \pi r} \). Where \( \mu = 4 \pi \times 10^{-7} \, {T·m/A} \), \( I = 5 \, {A} \), \( r = 0.02 \, {m} \). \( B = \frac{4 \pi \times 10^{-7} \times 5}{2 \pi \times 0.02} \). \( B = \frac{2 \times 10^{-6}}{0.02} \). \( B = 1 \times 10^{-4} \, {T} \). (b) Force on the Proton:} The force (\( F \)) on a charged particle moving in a magnetic field is given by: \( F = qvB \). Where \( q = 1.6 \times 10^{-19} \, {C} \) (charge of a proton), \( v = 1.5 \times 10^6 \, {m/s} \), \( B = 1 \times 10^{-4} \, {T} \). \( F = (1.6 \times 10^{-19}) \times (1.5 \times 10^6) \times (1 \times 10^{-4}) \). \( F = 2.4 \times 10^{-17} \, {N} \). (c) Direction of the Force:} The direction of the force on a proton moving parallel to a current-carrying wire can be determined using the right-hand rule. Point your thumb in the direction of the current, and your fingers in the direction of the proton's velocity. The force will be directed perpendicular to both, towards or away from the wire depending on the direction of the current. In this case, since the proton is moving parallel to the current, the force will be directed radially inward or outward, forming a circular path around the wire.",
        'paper': 2
    },
    84: {
        'question': r"A 0.5 kg block of aluminum (specific heat capacity \( c = 900 \, {J/kg·K} \)) is initially at a temperature of 20°C. It is heated until it reaches a temperature of 100°C. A. Calculate the amount of heat energy required to raise the temperature of the aluminum block to 100°C. B. If the heating process takes 5 minutes, calculate the average power required to heat the block. C. If the same amount of heat energy is used to heat a 0.3 kg block of copper (specific heat capacity \( c = 385 \, {J/kg·K} \)), calculate the final temperature of the copper block, assuming it also starts at 20°C.",
        'answer': r"(a) Heat Energy Required:} The amount of heat energy (\( Q \)) required is given by: \( Q = mc\Delta T \). Where \( m = 0.5 \, {kg} \), \( c = 900 \, {J/kg·K} \), \( \Delta T = 100°C - 20°C = 80 \, {K} \). \( Q = 0.5 \times 900 \times 80 \). \( Q = 36000 \, {J} \). (b) Average Power: The average power (\( P \)) required is given by: \( P = \frac{Q}{t} \). Where \( Q = 36000 \, {J} \), \( t = 5 \times 60 \, {s} = 300 \, {s} \). \( P = \frac{36000}{300} \). \( P = 120 \, {W} \). (c) Final Temperature of Copper: The same amount of heat energy (\( Q = 36000 \, {J} \)) is used to heat the copper block. The final temperature (\( T_f \)) can be found using: \( Q = mc\Delta T \). Where \( m = 0.3 \, {kg} \), \( c = 385 \, {J/kg·K} \), \( \Delta T = T_f - 20°C \). Rearranging for \( T_f \): \( 36000 = 0.3 \times 385 \times (T_f - 20) \). \( 36000 = 115.5 \times (T_f - 20) \). \( T_f - 20 = \frac{36000}{115.5} \). \( T_f - 20 = 311.69 \). \( T_f = 311.69 + 20 \). \( T_f = 331.69°C \).",
        'paper': 2
    },
    85: {
        'question': r"Consider a hydrogen atom in its ground state (\( n = 1 \)). The energy of the ground state is -13.6 eV. A. Calculate the wavelength of the photon required to ionize the hydrogen atom from its ground state. B. If the hydrogen atom is in the second excited state (\( n = 3 \)), calculate the energy required to ionize the atom. C. Determine the wavelength of the photon emitted when the hydrogen atom transitions from the third excited state (\( n = 4 \)) to the second excited state (\( n = 3 \)). D. Calculate the probability density of finding an electron at a distance \( r = a_0 \) (Bohr radius) from the nucleus in the ground state.",
        'answer': r"(a) Wavelength of Photon Required to Ionize the Ground State:} The energy required to ionize the hydrogen atom from its ground state is 13.6 eV. The energy of the photon (\( E \)) is given by: \( E = \frac{hc}{\lambda} \). Rearranging for \( \lambda \): \( \lambda = \frac{hc}{E} \). \( \lambda = \frac{4.135667696 \times 10^{-15} \times 3 \times 10^8}{13.6} \). \( \lambda \approx 91.2 \, {nm} \). (b) Energy Required to Ionize from the Second Excited State (\( n = 3 \)):} The energy of the nth state of the hydrogen atom is given by: \( E_n = -\frac{13.6}{n^2} \, {eV} \). For \( n = 3 \): \( E_3 = -\frac{13.6}{3^2} = -\frac{13.6}{9} \approx -1.51 \, {eV} \). The energy required to ionize from this state is: \( E_{{ionize}} = -E_3 = 1.51 \, {eV} \). (c) Wavelength of Photon Emitted during Transition from \( n = 4 \) to \( n = 3 \):} The energy difference between the levels is given by: \( \Delta E = E_4 - E_3 \). Where \( E_4 = -\frac{13.6}{4^2} = -\frac{13.6}{16} = -0.85 \, {eV} \). \( \Delta E = -0.85 - (-1.51) \). \( \Delta E = 0.66 \, {eV} \). The wavelength of the photon emitted is: \( \lambda = \frac{hc}{\Delta E} \). \( \lambda = \frac{4.135667696 \times 10^{-15} \times 3 \times 10^8}{0.66} \). \( \lambda \approx 1880 \, {nm} \). (d) Probability Density of Finding an Electron at \( r = a_0 \) in the Ground State:} The probability density (\( |\psi(r)|^2 \)) for the hydrogen atom in the ground state (\( n = 1 \)) at a distance \( r = a_0 \) (Bohr radius) is given by: \( \psi(r) = \frac{1}{\sqrt{\pi a_0^3}} e^{-r/a_0} \). At \( r = a_0 \): \( \psi(a_0) = \frac{1}{\sqrt{\pi a_0^3}} e^{-1} \). \( |\psi(a_0)|^2 = \left( \frac{1}{\sqrt{\pi a_0^3}} e^{-1} \right)^2 \). \( |\psi(a_0)|^2 = \frac{1}{\pi a_0^3 e^2} \).",
        'paper': 2
    },
    86: {
        'question': r"A double-slit experiment is performed using monochromatic light of wavelength 600 nm. The distance between the slits is 0.5 mm, and the screen is placed 2 meters away from the slits. A. Calculate the fringe spacing on the screen. B. If the width of each slit is 0.1 mm, calculate the angular width of the central maximum in the single-slit diffraction pattern. C. Determine the position of the first dark fringe on the screen. D. If the intensity of light at the central maximum is \( I_0 \), calculate the intensity of light at a point on the screen where the path difference is \( \frac{\lambda}{2} \).",
        'answer': r"(a) Fringe Spacing:} The fringe spacing (\( y \)) in a double-slit experiment is given by: \( y = \frac{\lambda D}{d} \). Where \( \lambda = 600 \, {nm} = 600 \times 10^{-9} \, {m} \), \( D = 2 \, {m} \), \( d = 0.5 \, {mm} = 0.5 \times 10^{-3} \, {m} \). \( y = \frac{600 \times 10^{-9} \times 2}{0.5 \times 10^{-3}} \). \( y = \frac{1200 \times 10^{-9}}{0.5 \times 10^{-3}} \). \( y = 2.4 \times 10^{-3} \, {m} \). \( y = 2.4 \, {mm} \). (b) Angular Width of Central Maximum:} The angular width (\( \theta \)) of the central maximum in a single-slit diffraction pattern is given by: \( \theta = \frac{2\lambda}{a} \). Where \( \lambda = 600 \, {nm} = 600 \times 10^{-9} \, {m} \), \( a = 0.1 \, {mm} = 0.1 \times 10^{-3} \, {m} \). \( \theta = \frac{2 \times 600 \times 10^{-9}}{0.1 \times 10^{-3}} \). \( \theta = \frac{1200 \times 10^{-9}}{0.1 \times 10^{-3}} \). \( \theta = 1.2 \times 10^{-2} \, {radians} \). (c) Position of the First Dark Fringe:} The position of the first dark fringe (\( y_1 \)) on the screen in a double-slit experiment is given by: \( y_1 = \frac{\lambda D}{d} \). Where \( \lambda = 600 \, {nm} = 600 \times 10^{-9} \, {m} \), \( D = 2 \, {m} \), \( d = 0.5 \, {mm} = 0.5 \times 10^{-3} \, {m} \). \( y_1 = \frac{600 \times 10^{-9} \times 2}{0.5 \times 10^{-3}} \). \( y_1 = \frac{1200 \times 10^{-9}}{0.5 \times 10^{-3}} \). \( y_1 = 2.4 \times 10^{-3} \, {m} \). \( y_1 = 2.4 \, {mm} \). (d) Intensity of Light at Path Difference \( \frac{\lambda}{2} \):} The intensity of light (\( I \)) at a point where the path difference is \( \frac{\lambda}{2} \) is given by: \( I = I_0 \cos^2 \left( \frac{\pi \delta}{\lambda} \right) \). Where \( \delta = \frac{\lambda}{2} \). \( I = I_0 \cos^2 \left( \frac{\pi \left( \frac{\lambda}{2} \right)}{\lambda} \right) \). \( I = I_0 \cos^2 \left( \frac{\pi}{2} \right) \). \( I = I_0 \cos^2(90°) \). \( I = I_0 \times 0 \). \( I = 0 \).",
        'paper': 2
    },
    87: {
        'question': r"A projectile is launched from the ground with an initial speed of 20 m/s at an angle of 30° above the horizontal. A. Calculate the time of flight of the projectile. B. Determine the maximum height reached by the projectile. C. Calculate the horizontal range of the projectile. D. Find the speed of the projectile at the highest point of its trajectory.",
        'answer': r"(a) Time of Flight:} The time of flight (\( T \)) for a projectile launched at an angle \( \theta \) with initial speed \( v_0 \) is given by: \( T = \frac{2v_0 \sin \theta}{g} \). Where \( v_0 = 20 \, {m/s} \), \( \theta = 30° \), \( g = 9.81 \, {m/s}^2 \). \( T = \frac{2 \times 20 \times \sin 30°}{9.81} \). \( T = \frac{40 \times 0.5}{9.81} \). \( T \approx 2.04 \, {s} \). (b) Maximum Height:} The maximum height (\( H \)) reached by the projectile is given by: \( H = \frac{v_0^2 \sin^2 \theta}{2g} \). Where \( v_0 = 20 \, {m/s} \), \( \theta = 30° \), \( g = 9.81 \, {m/s}^2 \). \( H = \frac{20^2 \times \sin^2 30°}{2 \times 9.81} \). \( H = \frac{400 \times 0.25}{19.62} \). \( H \approx 5.10 \, {m} \). (c) Horizontal Range:} The horizontal range (\( R \)) of the projectile is given by: \( R = \frac{v_0^2 \sin 2\theta}{g} \). Where \( v_0 = 20 \, {m/s} \), \( \theta = 30° \), \( g = 9.81 \, {m/s}^2 \). \( R = \frac{20^2 \times \sin 60°}{9.81} \). \( R = 400 \times \frac{\sqrt{3}}{2} \times \frac{1}{9.81} \). \( R \approx 35.28 \, {m} \). (d) Speed at the Highest Point:} The speed of the projectile at the highest point of its trajectory is given by the horizontal component of the initial velocity: \( v_x = v_0 \cos \theta \). Where \( v_0 = 20 \, {m/s} \), \( \theta = 30° \). \( v_x = 20 \times \cos 30° \). \( v_x = 20 \times \frac{\sqrt{3}}{2} \). \( v_x \approx 17.32 \, {m/s} \).",
        'paper': 2
    },
    88: {
        'question': r"A car is traveling around a circular track of radius 50 meters at a constant speed of 20 m/s. A. Calculate the centripetal acceleration of the car. B. Determine the centripetal force acting on the car if its mass is 1200 kg. C. If the coefficient of static friction between the tires and the track is 0.7, calculate the maximum speed the car can have without skidding. D. If the car takes 30 seconds to complete one lap, calculate the angular velocity of the car.",
        'answer': r"(a) Centripetal Acceleration:} The centripetal acceleration (\( a_c \)) is given by: \( a_c = \frac{v^2}{r} \). Where \( v = 20 \, {m/s} \), \( r = 50 \, {m} \). \( a_c = \frac{20^2}{50} \). \( a_c = \frac{400}{50} \). \( a_c = 8 \, {m/s}^2 \). (b) Centripetal Force:} The centripetal force (\( F_c \)) is given by: \( F_c = ma_c \). Where \( m = 1200 \, {kg} \), \( a_c = 8 \, {m/s}^2 \). \( F_c = 1200 \times 8 \). \( F_c = 9600 \, {N} \). (c) Maximum Speed without Skidding:} The maximum speed (\( v_{{max}} \)) without skidding is given by: \( F_{{friction}} = F_c \). \( \mu_s mg = mv_{{max}}^2 / r \). Where \( \mu_s = 0.7 \), \( m = 1200 \, {kg} \), \( g = 9.81 \, {m/s}^2 \), \( r = 50 \, {m} \). \( 0.7 \times 1200 \times 9.81 = mv_{{max}}^2 / 50 \). \( 0.7 \times 9.81 \times 50 = v_{{max}}^2 \). \( v_{{max}} = \sqrt{0.7 \times 9.81 \times 50} \). \( v_{{max}} \approx 18.55 \, {m/s} \). (d) Angular Velocity:} The angular velocity (\( \omega \)) is given by: \( \omega = \frac{2\pi}{T} \). Where \( T = 30 \, {s} \). \( \omega = \frac{2\pi}{30} \). \( \omega \approx 0.209 \, {rad/s} \).",
        'paper': 2
    },
    89: {
        'question': r"A 2.5 mol sample of an ideal gas is initially at a pressure of 1.2 atm and a temperature of 300 K. The gas is then compressed isothermally to a volume of 10 liters. A. Calculate the initial volume of the gas. B. Determine the final pressure of the gas after compression. C. Calculate the work done on the gas during the isothermal compression. D. If the gas is then heated at constant volume to a temperature of 400 K, calculate the final pressure.",
        'answer': r"(a) Initial Volume:} The initial volume (\( V_i \)) can be found using the ideal gas law: \( PV = nRT \). Where \( P = 1.2 \, {atm} \), \( n = 2.5 \, {mol} \), \( R = 0.0821 \, {L·atm/mol·K} \), \( T = 300 \, {K} \). \( V_i = \frac{nRT}{P} \). \( V_i = \frac{2.5 \times 0.0821 \times 300}{1.2} \). \( V_i = \frac{61.575}{1.2} \). \( V_i \approx 51.31 \, {L} \). (b) Final Pressure:} For an isothermal process, the initial and final states can be related by: \( P_i V_i = P_f V_f \). Where \( P_i = 1.2 \, {atm} \), \( V_i \approx 51.31 \, {L} \), \( V_f = 10 \, {L} \). \( P_f = \frac{P_i V_i}{V_f} \). \( P_f = \frac{1.2 \times 51.31}{10} \). \( P_f \approx 6.16 \, {atm} \). (c) Work Done on the Gas:} The work (\( W \)) done on the gas during isothermal compression is given by: \( W = nRT \ln \left( \frac{V_f}{V_i} \right) \). Where \( n = 2.5 \, {mol} \), \( R = 8.314 \, {J/mol·K} \) (using the SI units for work), \( T = 300 \, {K} \), \( V_i \approx 51.31 \, {L} \), \( V_f = 10 \, {L} \). Convert volumes to cubic meters (1 L = 0.001 m³): \( V_i \approx 0.05131 \, {m³} \), \( V_f = 0.01 \, {m³} \). \( W = 2.5 \times 8.314 \times 300 \times \ln \left( \frac{0.01}{0.05131} \right) \). \( W = 6235.5 \times \ln (0.195) \). \( W \approx 6235.5 \times (-1.633) \). \( W \approx -10176.5 \, {J} \). (Note: The negative sign indicates work done on the gas) (d) Final Pressure after Heating at Constant Volume:} Using the ideal gas law again for the heating process at constant volume: \( \frac{P_f}{T_f} = \frac{P_i}{T_i} \). Where \( P_i = 6.16 \, {atm} \) (from part b), \( T_i = 300 \, {K} \), \( T_f = 400 \, {K} \). \( P_f = P_i \left( \frac{T_f}{T_i} \right) \). \( P_f = 6.16 \times \left( \frac{400}{300} \right) \). \( P_f = 6.16 \times 1.333 \). \( P_f \approx 8.21 \, {atm} \).",
        'paper': 2
    },
    90: {
        'question': r"A capacitor of capacitance \( C = 10 \, \mu{F} \) is initially uncharged. It is connected in series with a resistor of resistance \( R = 5 \, {k}\Omega \) and a battery of \( V = 12 \, {V} \). A. Calculate the initial current flowing through the circuit immediately after the connection is made. B. Determine the time constant of the RC circuit. C. Calculate the charge on the capacitor after 10 milliseconds. D. Find the voltage across the resistor after 10 milliseconds.",
        'answer': r"(a) Initial Current: The initial current (\( I_0 \)) is given by Ohm's law: \( I_0 = \frac{V}{R} \). Where \( V = 12 \, {V} \), \( R = 5 \, {k}\Omega = 5000 \, \Omega \). \( I_0 = \frac{12}{5000} \). \( I_0 = 0.0024 \, {A} \). \( I_0 = 2.4 \, {mA} \). (b) Time Constant: The time constant (\( \tau \)) of an RC circuit is given by: \( \tau = RC \). Where \( R = 5 \, {k}\Omega = 5000 \, \Omega \), \( C = 10 \, \mu{F} = 10 \times 10^{-6} \, {F} \). \( \tau = 5000 \times 10 \times 10^{-6} \). \( \tau = 0.05 \, {s} \). \( \tau = 50 \, {ms} \). (c) Charge on the Capacitor: The charge (\( Q \)) on the capacitor at time \( t \) is given by: \( Q(t) = CV \left( 1 - e^{-t/RC} \right) \). Where \( C = 10 \, \mu{F} = 10 \times 10^{-6} \, {F} \), \( V = 12 \, {V} \), \( t = 10 \, {ms} = 0.01 \, {s} \), \( RC = 0.05 \, {s} \). \( Q(0.01) = 10 \times 10^{-6} \times 12 \times \left( 1 - e^{-0.01/0.05} \right) \). \( Q(0.01) = 120 \times 10^{-6} \times \left( 1 - e^{-0.2} \right) \). \( Q(0.01) \approx 120 \times 10^{-6} \times (1 - 0.8187) \). \( Q(0.01) \approx 120 \times 10^{-6} \times 0.1813 \). \( Q(0.01) \approx 21.76 \, \mu{C} \). (d) Voltage Across the Resistor: The voltage (\( V_R \)) across the resistor at time \( t \) is given by: \( V_R(t) = V e^{-t/RC} \). Where \( V = 12 \, {V} \), \( t = 10 \, {ms} = 0.01 \, {s} \), \( RC = 0.05 \, {s} \). \( V_R(0.01) = 12 \times e^{-0.01/0.05} \). \( V_R(0.01) = 12 \times e^{-0.2} \). \( V_R(0.01) \approx 12 \times 0.8187 \). \( V_R(0.01) \approx 9.82 \, {V} \).",
        'paper': 2
    }
}

for key, value in questions.items():
    question_text = value["question"]
    solution_text = value["answer"]
    Question.objects.create(
        subject=physics_subject,
        text=question_text,
        answer=solution_text,
        paper='2',
        # choices =value['choices']  # Setting paper to '1' as all questions are paper 1
    )





from main.models import Subject, Question

# Fetch the Math subject
try:
    math_subject = Subject.objects.get(name="Physics")
except Subject.DoesNotExist:
    print("The subject 'Math' does not exist.")
else:
    # Get all questions related to the Math subject
    math_questions = Question.objects.filter(subject=math_subject, paper ='2')
    math_questions.delete()
