# Generated by Django 4.0.1 on 2024-06-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_question_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
