# Generated by Django 4.0.1 on 2024-07-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_question_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='score',
        ),
        migrations.RemoveField(
            model_name='test',
            name='taken_at',
        ),
        migrations.RemoveField(
            model_name='test',
            name='user',
        ),
        migrations.AddField(
            model_name='test',
            name='paper',
            field=models.CharField(choices=[('1', 'Paper 1'), ('2', 'Paper 2')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(related_name='tests', to='main.Question'),
        ),
    ]
