# Generated by Django 4.0.1 on 2024-07-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_test_created_at_test_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='answers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
