# Generated by Django 4.0.1 on 2024-07-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_test_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='paper1_correct_answers',
            field=models.IntegerField(default=0),
        ),
    ]
